### ISSUE TITLE
Plugin Only Supports hpfod.com Cipher Suite If Running On Java 1.8

### ISSUE THREAD

**Issue by michael-a-marshall** [HPFOD/FoD-Jenkins#1]
Running Jenkins and plugin on Java 1.7 earlier causes an exception when attempting to access FoD API, stating that cipher suite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 is not supported. It should be possible to support this somehow on older Java versions by using third party software such as Bouncy Castle.

**Comment by ryancblack** [comment]
Documented as requirement of the plugin for Jenkins JVM level. Closing.
