### ISSUE TITLE
Java Logging Not Utilized

### ISSUE THREAD

**Issue by michael-a-marshall** [HPFOD/FoD-Jenkins#15]
Due to impatience, Java Logging API was not used for logging, at least not for logging related to global configuration. Get Java Logging working and switch calls to System.out to Java Logging API.

**Comment by michael-a-marshall** [comment]
Decided during 11 Feb status call that passwords and keys must be sanitized before being output. However, not utilizing Java Logging API is acceptable for now.

**Comment by ryancblack** [comment]
Closing as not required for go-live, will move as an enhancement to the canonical repo.
