### ISSUE TITLE
Handle Disabled Features in FoD

### ISSUE THREAD

**Issue by michael-a-marshall** [HPFOD/FoD-Jenkins#21]
Attempting to use features not enabled for a tenant may cause issues. Need to further investigate and determine how to handle them. It does not currently appear to be possible to determine if a feature is enabled or not before attempting to use it, so more complicated error handling is likely to be required.

**Comment by michael-a-marshall** [comment]
This should probably be handled at the same time as the fix for #4, which is for handling random errors returned from API calls better, possibly by retrying the API call. The fix for this may require making another call with modified parameters.

**Comment by ryancblack** [comment]
Tested as successful, closing.
