### ISSUE TITLE
Test Proxy Handling

### ISSUE THREAD

**Issue by michael-a-marshall** [HPFOD/FoD-Jenkins#22]
Need to set up different types of proxies to test against. Initial testing is just against a proxy without authentication.

**Comment by ryancblack** [comment]
Provided authenticated http proxy information to Michael directly. While out of scope for 1.0 we're prepared to test initial with Jenkins behind a proxy.

**Comment by ryancblack** [comment]
Closing as not required for go-live, will move as an enhancement to the canonical repo.
