### ISSUE TITLE
Configurable UI Field Help Text Not Customized

### ISSUE THREAD

**Issue by michael-a-marshall** [HPFOD/FoD-Jenkins#23]
Help text is set to default values. Need to set text for each field to something more ... helpful.

**Comment by ryancblack** [comment]
I'll write examples and seek approval for the verbiage used.

**Comment by michael-a-marshall** [comment]
TODO: Help text for file list to advise suggestions, and the impact of modification

**Comment by ryancblack** [comment]
DH will supply this information to use, on hold for now.

**Comment by drharper** [comment]
Field help text attached.
[Jenkins Help Text.docx](https://github.com/HPFOD/FoD-Jenkins/files/130780/Jenkins.Help.Text.docx)
