### ISSUE TITLE
Move Polling Interval from Global parameter to Post Build

### ISSUE THREAD

**Issue by drharper** [HPFOD/FoD-Jenkins#29]
We  want to be able to specify whether to wait for security assessment results on a per project basis. The simplest solution to this would be to move the Polling Interval parameter from global to post build. 

Alternatively add a 'Don't wait for assessment results' check box as part of post-build that would override the default polling with 0. This might be more intuitive for the user but I'm OK with either approach.

THIS IS A GO LIVE ISSUE.

**Comment by ryancblack** [comment]
Will implement tomorrow prior to Jenkins publish.

**Comment by ryancblack** [comment]
Checked in and validated.
