### ISSUE TITLE
FoD API Often Returns HTTP 500 When Accessing

### ISSUE THREAD

**Issue by michael-a-marshall** [HPFOD/FoD-Jenkins#4]
Investigate what causes HTTP 500 errors intermittently. Investigate if backoff timer is necessary to ensure more time between requests, and if anti-DDoS measures are in place that may require limiting remote calls.

**Comment by michael-a-marshall** [comment]
Rumor is that there are no anti-DDoS measures, so will need to put in place measures to accommodate API call failures. Main problem is loading list of applications and releases, so much of this problem will be addressed as part of fix for issue #11. This issue could also be addressed as part of fix for #17 if allowed to refactor HTTP client object usage.

**Comment by ryancblack** [comment]
Sufficiently mitigated with the current caching/retries. I am closing this for now and we can re-open on the other repo if needed.
