### ISSUE TITLE
Run Sonatype Scan Option Not Implemented

### ISSUE THREAD

**Issue by michael-a-marshall** [HPFOD/FoD-Jenkins#6]
This is a UI configuration element, but is currently ignored.

**Comment by michael-a-marshall** [comment]
Code committed.

**Comment by michael-a-marshall** [comment]
Updated code will add doSonatypeScan only if enabled. Still no code added to handle where a tenant does not have this feature, resulting in an HTTP 500 error, but that is documented in issue #21

**Comment by ryancblack** [comment]
Fixed param to "true" and tested, verified fixed.
